%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv
%
% Auto-generated by MATLAB on 15-Jun-2023 21:39:26

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "CH0Pressuredbar", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH0Pressuredbar";
opts.VariableTypes = ["string", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH0Pressuredbar = tbl.CH0Pressuredbar;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "CH1Chlorophyll_appb", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH1Chlorophyll_appb";
opts.VariableTypes = ["string", "string", "double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH1Chlorophyll_appb = tbl.CH1Chlorophyll_appb;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "CH2ConductivitymScm", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH2ConductivitymScm";
opts.VariableTypes = ["string", "string", "string", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH2ConductivitymScm = tbl.CH2ConductivitymScm;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "CH3TemperaturedegC", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH3TemperaturedegC";
opts.VariableTypes = ["string", "string", "string", "string", "double", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH3TemperaturedegC = tbl.CH3TemperaturedegC;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "CH4Oxygen_ConcentrationmgL", "Var7", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH4Oxygen_ConcentrationmgL";
opts.VariableTypes = ["string", "string", "string", "string", "string", "double", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var7", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH4Oxygen_ConcentrationmgL = tbl.CH4Oxygen_ConcentrationmgL;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "CH5Oxygen_Saturation", "Var8", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH5Oxygen_Saturation";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var8", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var8", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH5Oxygen_Saturation = tbl.CH5Oxygen_Saturation;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "CH6Practical_SalinityPSU", "Var9", "Var10", "Var11"];
opts.SelectedVariableNames = "CH6Practical_SalinityPSU";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "double", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var9", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH6Practical_SalinityPSU = tbl.CH6Practical_SalinityPSU;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "CH7Sound_Velocityms", "Var10", "Var11"];
opts.SelectedVariableNames = "CH7Sound_Velocityms";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var10", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH7Sound_Velocityms = tbl.CH7Sound_Velocityms;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "CH8Conductivity_25mScm", "Var11"];
opts.SelectedVariableNames = "CH8Conductivity_25mScm";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var11"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH8Conductivity_25mScm = tbl.CH8Conductivity_25mScm;

%% Clear temporary variables
clear opts tbl
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, 797];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "CH9Depthm"];
opts.SelectedVariableNames = "CH9Depthm";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\nacho\OneDrive\Escritorio\Geof\Semestre 11\Proyecto profe\5222_data_230324_194721_BahiaChoiseul_nocturno.csv", opts);

%% Convert to output type
CH9Depthm = tbl.CH9Depthm;

%% Clear temporary variables
clear opts tbl
%%
% Fecha y hora inicial
fechaInicio = datetime('2023-03-24 19:47:22');

% Fecha y hora final
fechaFinal = datetime('2023-03-25 09:02:22');

% Paso de tiempo (un minuto)
pasoTiempo = minutes(1);

% Crear el vector de tiempo
Tiempo = fechaInicio:pasoTiempo:fechaFinal;
Tiempo = Tiempo';
% Mostrar el vector de tiempo
disp(Tiempo);

clear pasoTiempo fechaInicio fechaFinal